### ISSUE TITLE
asyncio.TaskGroup limits usable python versions

### ISSUE THREAD

**Issue by WebSpider** [WEHI-ResearchComputing/FileSenderCli#21]
Currently this client uses `asyncio.TaskGroup` to manage parallel uploads and downloads.
Unfortunately, `asyncio.TaskGroup` was only added in python 3.11, making this client unusable/uninstallable for any system where the user does not have python3.11 available.

Without this feature, all python versions that receive security updates by the python team (to date: 3.8 and later) are able to run this client.

Please consider using `asyncio.gather()` / `asyncio.wait()` as a replacement for more compatibility

**Comment by multimeric** [comment]
Okay, I'd be willing to support the non-EOL Python versions assuming it doesn't require an enormous rewrite. I'll get to this when I have time, but if you already know what you need to fix then a PR would be quicker.

Out of interest though, what type of environment can't install or access a 2-year-old version?

**Comment by WebSpider** [comment]
> Out of interest though, what type of environment can't install or access a 2-year-old version?

For instance Almalinux 9 and Debian 11 don't have this in their repos.
